### ISSUE TITLE
Events - Special core events

### ISSUE THREAD

**Issue by aurelenc** [Cavonstavant/arcAAAAAAAAAAAAAAAAade#24]
When your program is running, keys must be mapped to the following actions:
- [x] Previous graphics library.
- [x] Next graphics library.
- [x] Previous game.
- [x] Next game.
- [x] Restart the game.
- [x] Go back to the menu.
- [x] Exit

**Comment by Cavonstavant** [comment]
| Key | Core Event |
|-------|----------------|
| 'h' / 'j' | Cycle through the available games |
| 'k' / 'l' | Cycle through the available graphic libraries |
| 'm' | Switch to the main menu |
| 'r' | Reload the current game |
